apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-common
  namespace: ticketing
data:
  # Default JWT secret (override via Secret in production)
  AUTH_JWT_SECRET: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
  # Auth service URL (used by user-service)
  AUTH_SERVICE_BASE_URL: "http://auth-service:8081"
  THEATRE_SERVICE_URL: "http://theatre-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"
